mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('registration/', include('registration.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create_question/',
         views.create_question,
         name='create_question'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/add_choice',
         views.add_choice_to_question,
         name='add_choice'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

registration/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'registration'

urlpatterns = [
    url('login/', auth_views.login, name='login'),
    url('logout/', auth_views.logout,
        {'template_name': 'registration/logged_out.html'}, name='logout'),
    url('signup/', views.signup, name='signup'),
    url('signup_success/', views.signup_success, name='signup_success')
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms


class CreateQuestionForm(forms.Form):
    question_text = forms.CharField(required=True)

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Question, Choice

from polls.forms import CreateQuestionForm


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last 5 published questions (not including
        those set to be published in the future).
        """

        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def create_question(request):
    if request.method == 'POST':
        form = CreateQuestionForm(request.POST)
        
        question = Question()
        question.question_text = request.POST['question_text']
        question.pub_date = timezone.now()
        question.save()

        choices = [Choice(choice_text=request.POST['choice1']),
                   Choice(choice_text=request.POST['choice2']),
                   Choice(choice_text=request.POST['choice3'])
                   ]

        for c in choices:
            c.question_id = question.id
            c.save()
            question.choice_set.add(c)

        return redirect(reverse('polls:index'))
    else:
        form = CreateQuestionForm()
        return render(request, 'polls/create_question.html', {'form': form})


def add_choice_to_question(request, question_id):
    return render(request, 'polls/%s/create_question.html' %(question_id))


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })

    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect with the saved POST data
        return HttpResponseRedirect(
            reverse('polls:results', args=(question.id,)))


def logout_view(request):
    logout(request)
    # redirect to success page
    # return HttpResponseRedirect(reverse('polls:login'))

polls/templates/polls/add_choice.html
<h2>Add Choice</h2>

<form action="{% url 'polls:detail' question.id %}">
	{% csrf_token %}
	<label for="new_choice">Choice:</label>
	<input type="text" name="new_choice">

	<input type="submit" value="Add">
</form>

polls/templates/polls/create_choice.html
{% load static %}

<h2>Add a choice to question '{{ question.question_text }}'</h2>

polls/templates/polls/create_question.html
{% load static %}

<h2>~Create a new Question~</h2>

<form action="" method="post">
	{% csrf_token %}
	{% for field in form %}
		<p>
			{{ field.label_tag }}<br />
			{{ field }}
		</p>
	{% endfor %}
	<label for="choice1">Choice 1</label>
	<input type="text" name="choice1"><br />
	<label for="choice2">Choice 2</label>
	<input type="text" name="choice2"/><br />
	<label for="choice3">Choice 3</label>
	<input type="text" name="choice3"/><br />
	<button type="submit">Submit</button>
</form>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
	<input type="submit" value="Vote" />	
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if user.is_authenticated %}
    You are logged in as {{ user.username }}.
{% endif %}
<br />
<ul>
	<a href="{% url 'registration:logout' %}">Logout</a>
	<a href="{% url 'polls:create_question' %}">Create new Question</a>
</ul>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/login_error.html
<p>Page cannot render for some reason... We'll figure it out later.</p>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>